#!/usr/bin/env python3
"""Render HA role-command scripts from the canonical config/site.yaml map.

The generated file is committed so Home Assistant needs no build dependency.  Do not edit it by
hand: update config/site.yaml and re-run this command instead.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


def load_devices(site: Path) -> dict[str, dict[str, Any]]:
    with site.open(encoding="utf-8") as source:
        payload = yaml.safe_load(source)
    zones = payload["site"]["zones"]
    active = next(zone for zone in zones.values() if zone.get("enabled", True))
    return active["ha"]["devices"]


def render(devices: dict[str, dict[str, Any]]) -> str:
    output = ["# Generated by scripts/render_r1_role_scripts.py from config/site.yaml. Do not edit.", ""]
    for role, device in devices.items():
        expected = device["expected_watts_on"]
        output.extend(
            [
                f"r1_set_{role}:",
                f"  alias: R1 set {role.replace('_', ' ')}",
                "  mode: restart",
                "  fields:",
                "    desired:",
                "      required: true",
                "      selector:",
                "        select:",
                "          options: [\"on\", \"off\"]",
                "  sequence:",
                "    - condition: template",
                "      value_template: >-",
                "        {{ desired == 'off' or "
                f"'{role}' == 'exhaust' or is_state('input_boolean.r1_thermal_latch', 'off') }}}}",
                f"    - action: switch.turn_{{{{ desired }}}}",
                "      target:",
                f"        entity_id: {device['switch']}",
                "    - wait_template: >-",
                f"        {{% set watts = states('{device['power']}') | float(none) %}}",
                "        {% if desired == 'on' %}",
                f"          {{{{ is_state('{device['switch']}', 'on') and watts is not none and {expected[0]} <= watts <= {expected[1]} }}}}",
                "        {% else %}",
                f"          {{{{ is_state('{device['switch']}', 'off') and watts is not none and watts <= 0.5 }}}}",
                "        {% endif %}",
                "      timeout: \"00:02:00\"",
                "      continue_on_timeout: true",
                "    - if:",
                "        - condition: template",
                "          value_template: \"{{ not wait.completed }}\"",
                "      then:",
                "        - action: persistent_notification.create",
                "          data:",
                f"            title: R1 command verification failed",
                f"            message: {role} did not reach the requested state and power range.",
                "",
            ]
        )
    return "\n".join(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, default=Path("config/site.yaml"))
    parser.add_argument("--output", type=Path, default=Path("ha/scripts/20_device_roles.yaml"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(load_devices(args.site)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
