#!/usr/bin/env python3
"""Render closed-loop HA role commands from the canonical config/site.yaml map.

The generated file is committed so Home Assistant needs no build dependency. Do not edit it by
hand: update config/site.yaml and re-run this command instead.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


def load_contract(site: Path) -> tuple[dict[str, dict[str, Any]], dict[str, Any]]:
    with site.open(encoding="utf-8") as source:
        payload = yaml.safe_load(source)
    zones = payload["site"]["zones"]
    active = next(zone for zone in zones.values() if zone.get("enabled", True))
    return active["ha"]["devices"], active["fallback"]["device_verification"]


def load_devices(site: Path) -> dict[str, dict[str, Any]]:
    """Compatibility helper used by the verifier tests."""

    return load_contract(site)[0]


def verification_template(device: dict[str, Any], off_threshold: float) -> list[str]:
    expected = device["expected_watts_on"]
    return [
        f"{{% set watts = states('{device['power']}') | float(none) %}}",
        "{% if desired == 'on' %}",
        f"  {{{{ is_state('{device['switch']}', 'on') and watts is not none and {expected[0]} <= watts <= {expected[1]} }}}}",
        "{% else %}",
        f"  {{{{ is_state('{device['switch']}', 'off') and watts is not none and watts <= {off_threshold} }}}}",
        "{% endif %}",
    ]


def failure_message(role: str, device: dict[str, Any], off_threshold: float) -> list[str]:
    expected = device["expected_watts_on"]
    label = role.replace("_", " ")
    switch = device["switch"]
    power = device["power"]
    return [
        f"{{% set switch_state = states('{switch}') %}}",
        f"{{% set power_state = states('{power}') %}}",
        "{% set watts = power_state | float(none) %}",
        "{% if switch_state in ['unknown', 'unavailable', 'none', ''] %}",
        f"  {label} ({switch}) is missing or unavailable after two commands. This is an integration/entity-ID failure.",
        "{% elif switch_state != desired %}",
        f"  {label} ({switch}) is present but remained {{{{ switch_state }}}} after two commands requesting {{{{ desired }}}}.",
        "{% elif watts is none %}",
        f"  {label} reached {{{{ desired }}}}, but its power telemetry ({power}) is {{{{ power_state }}}}; physical actuation is unverified.",
        f"{{% elif desired == 'on' and not ({expected[0]} <= watts <= {expected[1]}) %}}",
        f"  {label} entity is on but physical draw is {{{{ watts }}}} W, outside {expected[0]}–{expected[1]} W. This is a physical/load failure.",
        f"{{% elif desired == 'off' and watts > {off_threshold} %}}",
        f"  {label} entity is off but physical draw remains {{{{ watts }}}} W (limit {off_threshold} W). This is a physical/relay failure.",
        "{% else %}",
        f"  {label} did not pass state-and-power verification after two commands.",
        "{% endif %}",
    ]


def render(devices: dict[str, dict[str, Any]], verification: dict[str, Any]) -> str:
    settle_s = int(verification["settle_s"])
    attempts = int(verification["attempts"])
    off_threshold = verification["off_threshold_w"]
    if attempts != 2:
        raise ValueError("Issue #8 requires exactly two command attempts (one retry)")

    output = [
        "# Generated by scripts/render_r1_role_scripts.py from config/site.yaml. Do not edit.",
        "",
    ]
    for role, device in devices.items():
        verified = f"input_boolean.r1_{role}_verified"
        key = f"r1_command_{role}"
        cooldown = f"input_datetime.r1_last_alert_command_{role}"
        active = f"input_boolean.r1_alert_active_command_{role}"
        visible = f"input_boolean.r1_alert_visible_command_{role}"
        predicate = verification_template(device, off_threshold)
        message = failure_message(role, device, off_threshold)
        output.extend(
            [
                f"r1_set_{role}:",
                f"  alias: R1 set {role.replace('_', ' ')}",
                "  mode: restart",
                "  fields:",
                "    desired:",
                "      required: true",
                "      selector:",
                "        select:",
                '          options: ["on", "off"]',
                "    initial_command_sent:",
                "      required: false",
                "      default: false",
                "      selector:",
                "        boolean:",
                "  sequence:",
                "    - condition: template",
                "      value_template: >-",
                "        {{ desired == 'off' or "
                f"'{role}' == 'exhaust' or is_state('input_boolean.r1_thermal_latch', 'off') }}}}",
                "    - action: input_boolean.turn_off",
                "      target:",
                f"        entity_id: {verified}",
                "    - repeat:",
                "        sequence:",
                "          - if:",
                "              - condition: template",
                "                value_template: >-",
                "                  {{ not (repeat.first and",
                "                     initial_command_sent | default(false) | bool) }}",
                "            then:",
                f"              - action: switch.turn_{{{{ desired }}}}",
                "                continue_on_error: true",
                "                target:",
                f"                  entity_id: {device['switch']}",
                "          - delay:",
                f"              seconds: {settle_s}",
                "        until:",
                "          - condition: or",
                "            conditions:",
                "              - condition: template",
                "                value_template: >-",
                *[f"                  {line}" for line in predicate],
                "              - condition: template",
                f'                value_template: "{{{{ repeat.index >= {attempts} }}}}"',
                "    - if:",
                "        - condition: template",
                "          value_template: >-",
                *[f"            {line}" for line in predicate],
                "      then:",
                "        - action: input_boolean.turn_on",
                "          target:",
                f"            entity_id: {verified}",
                "        - action: script.r1_resolve_alert",
                "          data:",
                f"            key: {key}",
                f"            active_entity: {active}",
                f"            visible_entity: {visible}",
                f"            title: R1 command verified · {role.replace('_', ' ')}",
                f"            message: {role.replace('_', ' ')} now matches requested state and physical power.",
                "      else:",
                "        - action: input_boolean.turn_off",
                "          target:",
                f"            entity_id: {verified}",
                "        - action: script.r1_raise_alert",
                "          data:",
                f"            key: {key}",
                f"            cooldown_entity: {cooldown}",
                f"            active_entity: {active}",
                f"            visible_entity: {visible}",
                "            title: R1 command verification failed",
                "            message: >-",
                *[f"              {line}" for line in message],
                "",
                f"r1_toggle_{role}:",
                f"  alias: R1 toggle {role.replace('_', ' ')} through verification",
                "  mode: restart",
                "  sequence:",
                f"    - action: script.r1_set_{role}",
                "      data:",
                f"        desired: \"{{{{ 'off' if is_state('{device['switch']}', 'on') else 'on' }}}}\"",
                "",
            ]
        )
    return "\n".join(output)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", type=Path, default=Path("config/site.yaml"))
    parser.add_argument("--output", type=Path, default=Path("ha/scripts/20_device_roles.yaml"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    devices, verification = load_contract(args.site)
    args.output.write_text(render(devices, verification), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
